# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: choco install cygwin
  displayName: 'Install Cygwin'

- script: |
    refreshenv
    c:\tools\cygwin\setup.exe -q -P make
    c:\tools\cygwin\setup.exe -q -P curl
    c:\tools\cygwin\setup.exe -q -P wget
    c:\tools\cygwin\setup.exe -q -P patch
    c:\tools\cygwin\setup.exe -q -P git
    git config --global user.name "Eino"
    git config --global user.email eino.makitalo@eficode.com
    where bash
  displayName: 'Install cygwin tools'
  workingDirectory: c:\tools\cygwin

- bash:
    ./configure
    make -j
  displayName: 'Try to build'