# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: | 
    choco install cygwin
    choco install cyg-get
    cyg-get make curl wget patch git 
  displayName: 'Install Cygwin'

- pwsh: |
     $oldpath = (Get-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment' -Name PATH).path
     $newpath = "C:\tools\cygwin\bin;C:\tools\cygwin\sbin;;$oldpath" 
     Set-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment' -Name PATH -Value $newpath
  displayName: fix path

- pwsh: |
    $NewPathInRegistry = (Get-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment' -Name PATH).path
    Write-Host $NewPathInRegistry
  displayName: show path

- script: refreshenv
  displayName: 'refresh env'

- script: |  
    git config --global user.name "Eino"
    git config --global user.email eino.makitalo@eficode.com
  displayName: 'Git setup'

- script: where bash
  displayName: 'bash location'

- bash:
    ./configure
    make -j
  displayName: 'Try to build'